packages:
  - frontend
  - remote-frontend

onlyBuiltDependencies:
  - '@sentry/cli'
  - core-js
  - esbuild

patchedDependencies:
  '@virtuoso.dev/message-list': patches/@virtuoso.dev__message-list.patch
